name: Automerge

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  check_run:
    types:
      - completed
  status:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      checks: read
      contents: write
      pull-requests: write
      statuses: read

    steps:
      - id: automerge
        name: Auto-merge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ":robot: Automerge"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 0
          MERGE_REQUIRED_APPROVALS: 1
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: ":robot: Automerge"
