name: Sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    environment:
      name: sponsorkit
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Restore node_modules
        id: cache-node-modules-restore
        uses: actions/cache/restore@v4
        with:
          path: ./node_modules
          key: node-modules

      - name: Install dependencies
        run: pnpm install

      - name: Save node_modules
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: ./node_modules
          key: ${{ steps.cache-node-modules-restore.outputs.cache-primary-key }}

      - name: Update sponsors
        run: pnpm sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: simonhyll

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update sponsors.svg"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
