name: Test

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
