name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
